name: 'DevEnvironment'


services:
  dev:
    image: 'dev'
    restart: 'unless-stopped'
    volumes:
      - type: bind
        source: ./shared
        target: /home/ubuntu/app
    build:
      context: .
      dockerfile: Dockerfile
    user: ubuntu:ubuntu
    tty: true
    networks:
      - development
    attach: false

  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - development
      - mongo
    attach: false

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - development
      - postgres
    attach: false

  redis:
    image: redis:7.2
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - development
      - redis
    attach: false


networks:
  development:
  mongo:
  redis:
  postgres:
