name: 'services'

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - development
      - mongo
    volumes:
      - mongo:/var/lib/mongo

  postgres:
    image: postgres:17-alpine
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - development
      - postgres
    volumes:
      - postgres:/var/lib/postgres

  redis:
    image: redis:6-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - development
      - redis
    volumes:
      - redis:/var/lib/redis

  rabbitmq:
    image: rabbitmq:alpine
    hostname: redis
    ports:
      - 5672:5672   # rabbitmq
      - 15672:15672 # ui
    networks:
      - development
      - redis
    volumes:
      - rabbitmq:/var/lib/rabbitmq


networks:
  mongo:
  redis:
  postgres:
  development:
    external: true  # Indicate that this network is external

volumes:
  rabbitmq:
  redis:
  postgres:
  mongo: